## START: Set by rpmautospec
## (rpmautospec version 0.8.3)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 10;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

# This spec file has been modified by azldev to include build configuration overlays.
# Do not edit manually; changes may be overwritten.

# Generated by go2rpm 1.9.0
# Checks require a network connection
%bcond_with check
%global debug_package %{nil}

# https://github.com/valyala/fasthttp
%global goipath         github.com/valyala/fasthttp
Version:                1.48.0

%gometa

%global common_description %{expand:
Fast HTTP package for Go. Tuned for high performance. Zero memory allocations
in hot paths. Up to 10x faster than net/http.}

%global golicenses      LICENSE LICENSE-reuseport
%global godocs          examples README.md TODO SECURITY.md README-prefork.md

Name:           %{goname}
Release: %autorelease
Summary:        Fast HTTP package

# reuseport is also MIT
License:        MIT
URL:            %{gourl}
Source0:        %{gosource}


%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1
mv reuseport/LICENSE LICENSE-reuseport
mv prefork/README.md README-prefork.md

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/fasthttp %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE LICENSE-reuseport
%doc examples README.md TODO SECURITY.md README-prefork.md
%{_bindir}/fasthttp

%gopkgfiles

%changelog
## START: Generated by rpmautospec
* Thu May 14 2026 Daniel McIlvaney <damcilva@microsoft.com> - 1.48.0-10
- refesh all locks

* Fri Aug 15 2025 Maxwell G <maxwell@gtmx.me> - 1.48.0-12
- Rebuild for golang-1.25.0

* Thu Jul 24 2025 Fedora Release Engineering <releng@fedoraproject.org> - 1.48.0-11
- Rebuilt for https://fedoraproject.org/wiki/Fedora_43_Mass_Rebuild

* Fri Jan 17 2025 Fedora Release Engineering <releng@fedoraproject.org> - 1.48.0-10
- Rebuilt for https://fedoraproject.org/wiki/Fedora_42_Mass_Rebuild

* Thu Jul 18 2024 Fedora Release Engineering <releng@fedoraproject.org> - 1.48.0-9
- Rebuilt for https://fedoraproject.org/wiki/Fedora_41_Mass_Rebuild

* Wed Jan 24 2024 Fedora Release Engineering <releng@fedoraproject.org> - 1.48.0-7
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Sat Jan 20 2024 Fedora Release Engineering <releng@fedoraproject.org> - 1.48.0-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

%autochangelog

## END: Generated by rpmautospec
