FROM mcr.microsoft.com/azurelinux/base/core:3.0


RUN tdnf -y install acl
RUN tdnf -y install binutils
RUN tdnf -y install cdrkit
RUN tdnf -y install curl
RUN tdnf -y install diffutils
RUN tdnf -y install dosfstools
RUN tdnf -y install gawk
RUN tdnf -y install glibc-devel
RUN tdnf -y install genisoimage
RUN tdnf -y install git
RUN tdnf -y install golang
RUN tdnf -y install jq
RUN tdnf -y install kernel-headers
RUN tdnf -y install make
RUN tdnf -y install moby-cli
RUN tdnf -y install moby-engine
RUN tdnf -y install openssl
RUN tdnf -y install parted
RUN tdnf -y install pigz
RUN tdnf -y install qemu-img
RUN tdnf -y install rpm
RUN tdnf -y install rpm-build
RUN tdnf -y install sudo
RUN tdnf -y install tar
RUN tdnf -y install wget
RUN tdnf -y install xfsprogs
RUN tdnf -y install zstd
RUN tdnf -y install ca-certificates
RUN tdnf -y install tmux
RUN tdnf -y install procps-ng
