name: Check Package CGManifests

on:
  push:
    branches: [ main, dev, 1.0*]
  pull_request:
    branches: [ main, dev, 1.0*]

jobs:

  build:
    name: Validate Manifests
    runs-on: ubuntu-18.04
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Dump stuff
      env:
        C2: ${{ toJson(github) }}
      run: |
        echo "$C2"

    - name: Get base commit for PRs
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        git fetch origin ${{ github.base_ref }}
        echo "::set-env name=base_sha::$(git rev-parse origin/${{ github.base_ref }})"
        echo "Merging ${{ github.sha }} into ${{ github.base_ref }}"
        echo "What about ${{ github.head_ref }}?"

    - name: Get base commit for Pushes
      if: ${{ github.event_name == 'push' }}
      run: |
        git fetch origin ${{ github.ref }}
        echo "::set-env name=base_sha::$(git rev-parse origin/${{ github.base_ref }}~1)"
        echo "Merging ${{ github.sha }} into ${{ env.base_sha }}"
        echo "What about ${{ github.head_ref }}?"

    - name: Get the changed files
      run: |
        echo "Files changed: '$(git diff-tree --no-commit-id --name-only -r ${{ env.base_sha }} ${{ github.sha }})'"
        echo "::set-env name=updated-specs::$(git diff-tree --no-commit-id --name-only -r ${{ env.base_sha }} ${{ github.sha }} | grep "\.spec$")"
        echo "Files to validate: '${{ env.updated-specs }}'"

    - name: Check each spec
      run: |
        .github/workflows/validate-cg-manifest.sh ${{ env.updated-specs }}