## START: Set by rpmautospec
## (rpmautospec version 0.8.3)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 32;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

# This spec file has been modified by azldev to include build configuration overlays.
# Do not edit manually; changes may be overwritten.

%global srcname dj_database_url

Name:           python-django-database-url
Version:        0.5.0
Release: %autorelease
Summary:        Use Database URLs in your Django Application
# Automatically converted from old format: BSD - review is highly recommended.
License:        LicenseRef-Callaway-BSD
URL:            https://github.com/kennethreitz/dj-database-url
Source0:        https://github.com/kennethreitz/dj-database-url/archive/v%{version}.tar.gz#/dj-database-url-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  python3-devel

%global _description %{expand:
This simple Django utility allows you to utilize the 12factor inspired
DATABASE_URL environment variable to configure your Django application.}

%description %_description

%package -n python3-django-database-url
Summary:        %summary
Requires:       python3-django
Obsoletes:      python-django-database-url < 0.4.2-4
Obsoletes:      python2-django-database-url < 0.4.2-4

%description -n python3-django-database-url %_description

%prep
%autosetup -n dj-database-url-%{version}

%generate_buildrequires
%pyproject_buildrequires

%build
%pyproject_wheel

%install
%pyproject_install
%pyproject_save_files -l %{srcname}

%check
%pyproject_check_import
%{py3_test_envvars} %{python3} test_dj_database_url.py

%files -n python3-django-database-url -f %{pyproject_files}
%doc README.rst

%changelog
## START: Generated by rpmautospec
* Thu May 14 2026 Daniel McIlvaney <damcilva@microsoft.com> - 0.5.0-32
- refesh all locks

* Fri Sep 19 2025 Python Maint <python-maint@redhat.com> - 0.5.0-30
- Rebuilt for Python 3.14.0rc3 bytecode

* Fri Aug 15 2025 Python Maint <python-maint@redhat.com> - 0.5.0-29
- Rebuilt for Python 3.14.0rc2 bytecode

* Fri Jul 25 2025 Fedora Release Engineering <releng@fedoraproject.org> - 0.5.0-28
- Rebuilt for https://fedoraproject.org/wiki/Fedora_43_Mass_Rebuild

%autochangelog

## END: Generated by rpmautospec
